version: "3.9"

services:
  # --------------------------
  # Postgres for Airflow metadata DB
  # --------------------------
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container2
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  # --------------------------
  # MongoDB for DAG storage
  # --------------------------
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: books_shop
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --------------------------
  # Airflow Webserver
  # --------------------------
  airflow-webserver:
    image: apache/airflow:2.10.2-python3.11
#    image: apache/airflow:3.1.3-python3.11
    restart: always
    depends_on:
      - postgres
#      - mongodb
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: my-super-secret-key
    user: "50000:50000"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install -r /requirements.txt &&  pip install --upgrade pip &&
               airflow db init &&
               airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
               airflow webserver"

  # --------------------------
  # Airflow Scheduler
  # --------------------------
  airflow-scheduler:
    image: apache/airflow:2.10.2-python3.11
#    image: apache/airflow:3.1.3-python3.11
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: my-super-secret-key
    user: "50000:50000"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install -r /requirements.txt &&  pip install --upgrade pip &&
      airflow scheduler"

# --------------------------
# Volumes
# --------------------------
volumes:
  postgres_data:
  mongo_data:
